services:
  php:
    container_name: spl-php
    restart: on-failure
    build:
      context: ./docker/php
      target: php
      args:
        - GROUP_ID=${DOCKER_GROUP_ID}
        - USER_ID=${DOCKER_USER_ID}
    working_dir: /sparallel
    volumes:
      - ./:/sparallel
    command: [ "php", "/sparallel/docker/php/docker-php-stub.php" ]

  server:
    container_name: spl-server
    restart: always
    build:
      context: ./docker/php
      target: php
      args:
        - GROUP_ID=${DOCKER_GROUP_ID}
        - USER_ID=${DOCKER_USER_ID}
    working_dir: /sparallel/libs/server
    volumes:
      - ./:/sparallel
    command: [ "./sparallel", "--env=/sparallel/workbench/config/.env.sparallel", "start" ]
